const aircraftData = {
  jetstream31: {
    Price: [323000, "USD"],
    Seats: [19, "passengers"],
    Range: [1260, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [20000, "ft"],
    "Fuel Consumption": [16.83, "lbs/km"],
    "Cruise Speed": [405, "kph"],
    "A-Check": [13976, "USD"],
    "Maintenance Interval": [320, "hours"],
    "Crew Total": [4, "people"],
    Pilots: [2, "people"],
    Crew: [1, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.21, "kg/pax/km"],
    Wingspan: [14, "m"],
    Length: [16, "m"]
  },
    erj135er: {
    Price: [352585, "USD"],
    Seats: [37, "passengers"],
    Range: [2650, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [9.54, "lbs/km"],
    "Cruise Speed": [910, "kph"],
    "A-Check": [38784, "USD"],
    "Maintenance Interval": [460, "hours"],
    "Crew Total": [7, "people"],
    Pilots: [2, "people"],
    Crew: [2, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    Wingspan: [26, "m"],
    Length: [20, "m"]
  },
  cessna: {
    Price: [51000, "USD"],
    Seats: [3, "passengers"],
    Range: [1000, "km"],
    "Runway Required": [1281, "ft"],
    "Service Ceiling": [14100, "ft"],
    "Fuel Consumption": [3.76, "lbs/km"],
    "Cruise Speed": [221, "kph"],
    "A-Check": [4682, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [1, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.05, "kg/pax/km"],
    "Wingspan": [8, "m"],
    "Length": [11, "m"]
  },
  phenom: {
    Price: [68000, "USD"],
    Seats: [4, "passengers"],
    Range: [2182, "km"],
    "Runway Required": [3480, "ft"],
    "Service Ceiling": [41000, "ft"],
    "Fuel Consumption": [7.20, "lbs/km"],
    "Cruise Speed": [708, "kph"],
    "A-Check": [1900, "USD"],
    "Maintenance Interval": [490, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [13, "m"],
    "Length": [12, "m"]
  },
  phenom300: {
    Price: [102000, "USD"],
    Seats: [6, "passengers"],
    Range: [3334, "km"],
    "Runway Required": [3900, "ft"],
    "Service Ceiling": [41000, "ft"],
    "Fuel Consumption": [8.72, "lbs/km"],
    "Cruise Speed": [851, "kph"],
    "A-Check": [3658, "USD"],
    "Maintenance Interval": [460, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [16, "m"],
    "Length": [16, "m"]
  },
  embx: {
    Price: [85000, "USD"],
    Seats: [5, "passengers"],
    Range: [2352, "km"],
    "Runway Required": [4250, "ft"],
    "Service Ceiling": [33500, "ft"],
    "Fuel Consumption": [7.76, "lbs/km"],
    "Cruise Speed": [329, "kph"],
    "A-Check": [6588, "USD"],
    "Maintenance Interval": [350, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [12, "m"],
    "Length": [14, "m"]
  },
  hondajet: {
    Price: [100000, "USD"],
    Seats: [6, "passengers"],
    Range: [2700, "km"],
    "Runway Required": [3930, "ft"],
    "Service Ceiling": [43000, "ft"],
    "Fuel Consumption": [6.00, "lbs/km"],
    "Cruise Speed": [782, "kph"],
    "A-Check": [5000, "USD"],
    "Maintenance Interval": [450, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [13, "m"],
    "Length": [12, "m"]
  },
  an74vip: {
    Price: [100722, "USD"],
    Seats: [12, "passengers"],
    Range: [3300, "km"],
    "Runway Required": [4900, "ft"],
    "Service Ceiling": [30000, "ft"],
    "Fuel Consumption": [7.68, "lbs/km"],
    "Cruise Speed": [539, "kph"],
    "A-Check": [18130, "USD"],
    "Maintenance Interval": [350, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [28, "m"],
    "Length": [32, "m"]
  },
  an74200: {
    Price: [134296, "USD"],
    Seats: [16, "passengers"],
    Range: [3300, "km"],
    "Runway Required": [4650, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [10.56, "lbs/km"],
    "Cruise Speed": [539, "kph"],
    "A-Check": [24174, "USD"],
    "Maintenance Interval": [320, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.14, "kg/pax/km"],
    "Wingspan": [28, "m"],
    "Length": [32, "m"]
  },
  saab340: {
    Price: [109241, "USD"],
    Seats: [37, "passengers"],
    Range: [1730, "km"],
    "Runway Required": [4600, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [13.65, "lbs/km"],
    "Cruise Speed": [425, "kph"],
    "A-Check": [19664, "USD"],
    "Maintenance Interval": [380, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.19, "kg/pax/km"],
    "Wingspan": [20, "m"],
    "Length": [21, "m"]
  },
  legacy450: {
    Price: [110501, "USD"],
    Seats: [7, "passengers"],
    Range: [4260, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [40000, "ft"],
    "Fuel Consumption": [7.60, "lbs/km"],
    "Cruise Speed": [837, "kph"],
    "A-Check": [4420, "USD"],
    "Maintenance Interval": [520, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [20, "m"],
    "Length": [20, "m"]
  },
  beech1900: {
    Price: [119896, "USD"],
    Seats: [19, "passengers"],
    Range: [2907, "km"],
    "Runway Required": [4500, "ft"],
    "Service Ceiling": [30000, "ft"],
    "Fuel Consumption": [9.36, "lbs/km"],
    "Cruise Speed": [500, "kph"],
    "A-Check": [21582, "USD"],
    "Maintenance Interval": [380, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    "Wingspan": [18, "m"],
    "Length": [18, "m"]
  },
  beech1900d: {
    Price: [111024, "USD"],
    Seats: [19, "passengers"],
    Range: [2776, "km"],
    "Runway Required": [4500, "ft"],
    "Service Ceiling": [30000, "ft"],
    "Fuel Consumption": [13.65, "lbs/km"],
    "Cruise Speed": [470, "kph"],
    "A-Check": [15544, "USD"],
    "Maintenance Interval": [490, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.19, "kg/pax/km"],
    "Wingspan": [18, "m"],
    "Length": [18, "m"]
  },
  beech1900c: {
    Price: [323000, "USD"],
    Seats: [19, "passengers"],
    Range: [2500, "km"],
    "Runway Required": [4500, "ft"],
    "Service Ceiling": [30000, "ft"],
    "Fuel Consumption": [16.96, "lbs/km"],
    "Cruise Speed": [621, "kph"],
    "A-Check": [14346, "USD"],
    "Maintenance Interval": [450, "hours"],
    "Crew Total": [4, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    Wingspan: [18, "m"],
    Length: [18, "m"]
  },
  saabscan: {
    Price: [113217, "USD"],
    Seats: [32, "passengers"],
    Range: [2510, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [20000, "ft"],
    "Fuel Consumption": [9.27, "lbs/km"],
    "Cruise Speed": [477, "kph"],
    "A-Check": [42456, "USD"],
    "Maintenance Interval": [210, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    "Wingspan": [21, "m"],
    "Length": [28, "m"]
  },
  atr42320: {
    Price: [122121, "USD"],
    Seats: [46, "passengers"],
    Range: [1945, "km"],
    "Runway Required": [6500, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [9.90, "lbs/km"],
    "Cruise Speed": [483, "kph"],
    "A-Check": [20760, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.14, "kg/pax/km"],
    "Wingspan": [23, "m"],
    "Length": [25, "m"]
  },
  atr42500: {
    Price: [122750, "USD"],
    Seats: [50, "passengers"],
    Range: [1611, "km"],
    "Runway Required": [6500, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [14.88, "lbs/km"],
    "Cruise Speed": [550, "kph"],
    "A-Check": [21482, "USD"],
    "Maintenance Interval": [340, "hours"],
    "Crew Total": [4, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    "Wingspan": [22, "m"],
    "Length": [24, "m"]
  },
  atr42400: {
    Price: [133060, "USD"],
    Seats: [48, "passengers"],
    Range: [1945, "km"],
    "Runway Required": [6500, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [16.96, "lbs/km"],
    "Cruise Speed": [556, "kph"],
    "A-Check": [15968, "USD"],
    "Maintenance Interval": [500, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    "Wingspan": [23, "m"],
    "Length": [25, "m"]
  },
  atr42600: {
    Price: [208303, "USD"],
    Seats: [50, "passengers"],
    Range: [2000, "km"],
    "Runway Required": [6500, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [14.25, "lbs/km"],
    "Cruise Speed": [559, "kph"],
    "A-Check": [8332, "USD"],
    "Maintenance Interval": [550, "hours"],
    "Crew Total": [3, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.19, "kg/pax/km"],
    Wingspan: [23, "m"],
    Length: [25, "m"]
  },
  dhc8: {
    Price: [127710, "USD"],
    Seats: [37, "passengers"],
    Range: [1889, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [16.96, "lbs/km"],
    "Cruise Speed": [505, "kph"],
    "A-Check": [22350, "USD"],
    "Maintenance Interval": [380, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    "Wingspan": [22, "m"],
    "Length": [26, "m"]
  },
  dhc8q200: {
    Price: [124381, "USD"],
    Seats: [37, "passengers"],
    Range: [1713, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [17.51, "lbs/km"],
    "Cruise Speed": [585, "kph"],
    "A-Check": [14926, "USD"],
    "Maintenance Interval": [480, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.21, "kg/pax/km"],
    "Wingspan": [22, "m"],
    "Length": [26, "m"]
  },
  dhc8q300: {
    Price: [180374, "USD"],
    Seats: [50, "passengers"],
    Range: [1558, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [13.86, "lbs/km"],
    "Cruise Speed": [512, "kph"],
    "A-Check": [27056, "USD"],
    "Maintenance Interval": [370, "hours"],
    "Crew Total": [4, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.18, "kg/pax/km"],
    Wingspan: [26, "m"],
    Length: [27, "m"]
  },
  f27: {
    Price: [127943, "USD"],
    Seats: [44, "passengers"],
    Range: [1890, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [14.72, "lbs/km"],
    "Cruise Speed": [392, "kph"],
    "A-Check": [33266, "USD"],
    "Maintenance Interval": [350, "hours"],
    "Crew Total": [4, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    "Wingspan": [25, "m"],
    "Length": [28, "m"]
  },
  l25b: {
    Price: [137633, "USD"],
    Seats: [8, "passengers"],
    Range: [2684, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [6.65, "lbs/km"],
    "Cruise Speed": [789, "kph"],
    "A-Check": [33720, "USD"],
    "Maintenance Interval": [320, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.09, "kg/pax/km"],
    "Wingspan": [47, "m"],
    "Length": [53, "m"]
  },
  sn601: {
    Price: [149020, "USD"],
    Seats: [14, "passengers"],
    Range: [2555, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [29000, "ft"],
    "Fuel Consumption": [7.60, "lbs/km"],
    "Cruise Speed": [684, "kph"],
    "A-Check": [35020, "USD"],
    "Maintenance Interval": [360, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [14, "m"],
    "Length": [13, "m"]
  },
  legacy500: {
    Price: [128115, "USD"],
    Seats: [8, "passengers"],
    Range: [5186, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [40000, "ft"],
    "Fuel Consumption": [7.60, "lbs/km"],
    "Cruise Speed": [837, "kph"],
    "A-Check": [5124, "USD"],
    "Maintenance Interval": [510, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [21, "m"],
    "Length": [20, "m"]
  },
  l1329jetstar: {
    Price: [132130, "USD"],
    Seats: [10, "passengers"],
    Range: [4585, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [9.09, "lbs/km"],
    "Cruise Speed": [957, "kph"],
    "A-Check": [40960, "USD"],
    "Maintenance Interval": [320, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    "Wingspan": [18, "m"],
    "Length": [17, "m"]
  },
  emb120: {
    Price: [134440, "USD"],
    Seats: [30, "passengers"],
    Range: [1481, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [14.00, "lbs/km"],
    "Cruise Speed": [535, "kph"],
    "A-Check": [22854, "USD"],
    "Maintenance Interval": [390, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.18, "kg/pax/km"],
    "Wingspan": [20, "m"],
    "Length": [20, "m"]
  },
  f27200: {
    Price: [135138, "USD"],
    Seats: [40, "passengers"],
    Range: [1926, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [16.00, "lbs/km"],
    "Cruise Speed": [451, "kph"],
    "A-Check": [40542, "USD"],
    "Maintenance Interval": [350, "hours"],
    "Crew Total": [4, "people"],
    Engineers: [1, "people"],
    Tech: [3, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    Wingspan: [25, "m"],
    Length: [28, "m"]
  },
  kingair: {
    Price: [187000, "USD"],
    Seats: [11, "passengers"],
    Range: [3340, "km"],
    "Runway Required": [3300, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [16.16, "lbs/km"],
    "Cruise Speed": [626, "kph"],
    "A-Check": [17766, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [3, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.15, "kg/pax/km"],
    Wingspan: [null, "m"],
    Length: [null, "m"]
  },
  praetor500: {
    Price: [198115, "USD"],
    Seats: [7, "passengers"],
    Range: [6186, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [40000, "ft"],
    "Fuel Consumption": [7.60, "lbs/km"],
    "Cruise Speed": [837, "kph"],
    "A-Check": [34216, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [3, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    Wingspan: [21, "m"],
    Length: [21, "m"]
  },
  praetor600: {
    Price: [218115, "USD"],
    Seats: [8, "passengers"],
    Range: [7441, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [42000, "ft"],
    "Fuel Consumption": [8.00, "lbs/km"],
    "Cruise Speed": [794, "kph"],
    "A-Check": [34216, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [3, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.12, "kg/pax/km"],
    Wingspan: [21, "m"],
    Length: [21, "m"]
  },
  dc1: {
    Price: [204000, "USD"],
    Seats: [12, "passengers"],
    Range: [1500, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [20000, "ft"],
    "Fuel Consumption": [18.00, "lbs/km"],
    "Cruise Speed": [297, "kph"],
    "A-Check": [4628, "USD"],
    "Maintenance Interval": [200, "hours"],
    "Crew Total": [3, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.22, "kg/pax/km"],
    Wingspan: [18, "m"],
    Length: [26, "m"]
  },
  challenger300: {
    Price: [223915, "USD"],
    Seats: [16, "passengers"],
    Range: [3000, "km"],
    "Runway Required": [3500, "ft"],
    "Service Ceiling": [40000, "ft"],
    "Fuel Consumption": [10.10, "lbs/km"],
    "Cruise Speed": [945, "kph"],
    "A-Check": [16794, "USD"],
    "Maintenance Interval": [480, "hours"],
    "Crew Total": [3, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.12, "kg/pax/km"],
    Wingspan: [20, "m"],
    Length: [19, "m"]
  },
  cessna208b: {
    Price: [238000, "USD"],
    Seats: [14, "passengers"],
    Range: [2000, "km"],
    "Runway Required": [2990, "ft"],
    "Service Ceiling": [16000, "ft"],
    "Fuel Consumption": [10.70, "lbs/km"],
    "Cruise Speed": [327, "kph"],
    "A-Check": [6962, "USD"],
    "Maintenance Interval": [390, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.12, "kg/pax/km"],
    "Wingspan": [13, "m"],
    "Length": [16, "m"]
  },
  dc2: {
    Price: [238000, "USD"],
    Seats: [14, "passengers"],
    Range: [1750, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [20000, "ft"],
    "Fuel Consumption": [15.64, "lbs/km"],
    "Cruise Speed": [273, "kph"],
    "A-Check": [6226, "USD"],
    "Maintenance Interval": [290, "hours"],
    "Crew Total": [3, "people"],
    Pilots: [3, "people"],
    Crew: [1, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.21, "kg/pax/km"],
    Wingspan: [19, "m"],
    Length: [26, "m"]
  },
  dc5: {
    Price: [374000, "USD"],
    Seats: [22, "passengers"],
    Range: [2575, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [20000, "ft"],
    "Fuel Consumption": [18.54, "lbs/km"],
    "Cruise Speed": [358, "kph"],
    "A-Check": [12266, "USD"],
    "Maintenance Interval": [230, "hours"],
    "Crew Total": [8, "people"],
    Pilots: [3, "people"],
    Crew: [2, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.22, "kg/pax/km"],
    Wingspan: [19, "m"],
    Length: [24, "m"]
  },
  tu104: {
    Price: [241193, "USD"],
    Seats: [50, "passengers"],
    Range: [2750, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [16.80, "lbs/km"],
    "Cruise Speed": [816, "kph"],
    "A-Check": [77182, "USD"],
    "Maintenance Interval": [330, "hours"],
    "Crew Total": [8, "people"],
    Pilots: [2, "people"],
    Crew: [2, "people"],
    Engineers: [1, "people"],
    Tech: [3, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    Wingspan: [40, "m"],
    Length: [53, "m"]
  },
  il114: {
    Price: [255147, "USD"],
    Seats: [64, "passengers"],
    Range: [1000, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [13.95, "lbs/km"],
    "Cruise Speed": [490, "kph"],
    "A-Check": [36996, "USD"],
    "Maintenance Interval": [470, "hours"],
    "Crew Total": [7, "people"],
    Pilots: [2, "people"],
    Crew: [2, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.19, "kg/pax/km"],
    Wingspan: [27, "m"],
    Length: [30, "m"]
  },
  il114100: {
    Price: [382720, "USD"],
    Seats: [64, "passengers"],
    Range: [2000, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [9.60, "lbs/km"],
    "Cruise Speed": [465, "kph"],
    "A-Check": [40186, "USD"],
    "Maintenance Interval": [470, "hours"],
    "Crew Total": [7, "people"],
    Pilots: [2, "people"],
    Crew: [2, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.12, "kg/pax/km"],
    Wingspan: [27, "m"],
    Length: [30, "m"]
  },
  dhc7: {
    Price: [259197, "USD"],
    Seats: [54, "passengers"],
    Range: [1400, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [22000, "ft"],
    "Fuel Consumption": [14.70, "lbs/km"],
    "Cruise Speed": [396, "kph"],
    "A-Check": [53136, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [6, "people"],
    Pilots: [2, "people"],
    Crew: [1, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.19, "kg/pax/km"],
    Wingspan: [25, "m"],
    Length: [28, "m"]
  },
  f27500: {
    Price: [336145, "USD"],
    Seats: [52, "passengers"],
    Range: [1826, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [15.64, "lbs/km"],
    "Cruise Speed": [482, "kph"],
    "A-Check": [87398, "USD"],
    "Maintenance Interval": [380, "hours"],
    "Crew Total": [8, "people"],
    Pilots: [2, "people"],
    Crew: [2, "people"],
    Engineers: [1, "people"],
    Tech: [3, "people"],
    "CO2 Emission": [0.21, "kg/pax/km"],
    Wingspan: [27, "m"],
    Length: [28, "m"]
  },
  legacy600: {
    Price: [360159, "USD"],
    Seats: [13, "passengers"],
    Range: [6060, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [40000, "ft"],
    "Fuel Consumption": [8.00, "lbs/km"],
    "Cruise Speed": [784, "kph"],
    "A-Check": [34216, "USD"],
    "Maintenance Interval": [490, "hours"],
    "Crew Total": [5, "people"],
    Pilots: [2, "people"],
    Crew: [1, "people"],
    Engineers: [1, "people"],
    Tech: [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    Wingspan: [26, "m"],
    Length: [21, "m"]
  },
  citationx: {
    Price: [378968, "USD"],
    Seats: [12, "passengers"],
    Range: [6020, "km"],
    "Runway Required": [4000, "ft"],
    "Service Ceiling": [35000, "ft"],
    "Fuel Consumption": [7.68, "lbs/km"],
    "Cruise Speed": [947, "kph"],
    "A-Check": [58740, "USD"],
    "Maintenance Interval": [360, "hours"],
    "Crew Total": [6, "people"],
    Pilots: [2, "people"],
    Crew: [1, "people"],
    Engineers: [1, "people"],
    Tech: [2, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    Wingspan: [22, "m"],
    Length: [18, "m"]
  },
};