const aircraftData = {
  cessna: {
    Price: [51000, "USD"],
    Seats: [3, "passengers"],
    Range: [1000, "km"],
    "Runway Required": [1281, "ft"],
    "Service Ceiling": [14100, "ft"],
    "Fuel Consumption": [3.76, "lbs/km"],
    "Cruise Speed": [221, "kph"],
    "A-Check": [4682, "USD"],
    "Maintenance Interval": [400, "hours"],
    "Crew Total": [1, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.05, "kg/pax/km"],
    "Wingspan": [8, "m"],
    "Length": [11, "m"]
  },
  phenom: {
    Price: [68000, "USD"],
    Seats: [4, "passengers"],
    Range: [2182, "km"],
    "Runway Required": [3480, "ft"],
    "Service Ceiling": [41000, "ft"],
    "Fuel Consumption": [7.20, "lbs/km"],
    "Cruise Speed": [708, "kph"],
    "A-Check": [1900, "USD"],
    "Maintenance Interval": [490, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [13, "m"],
    "Length": [12, "m"]
  },
  phenom300: {
    Price: [102000, "USD"],
    Seats: [6, "passengers"],
    Range: [3334, "km"],
    "Runway Required": [3900, "ft"],
    "Service Ceiling": [41000, "ft"],
    "Fuel Consumption": [8.72, "lbs/km"],
    "Cruise Speed": [851, "kph"],
    "A-Check": [3658, "USD"],
    "Maintenance Interval": [460, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [16, "m"],
    "Length": [16, "m"]
  },
  embx: {
    Price: [85000, "USD"],
    Seats: [5, "passengers"],
    Range: [2352, "km"],
    "Runway Required": [4250, "ft"],
    "Service Ceiling": [33500, "ft"],
    "Fuel Consumption": [7.76, "lbs/km"],
    "Cruise Speed": [329, "kph"],
    "A-Check": [6588, "USD"],
    "Maintenance Interval": [350, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [12, "m"],
    "Length": [14, "m"]
  },
  hondajet: {
    Price: [100000, "USD"],
    Seats: [6, "passengers"],
    Range: [2700, "km"],
    "Runway Required": [3930, "ft"],
    "Service Ceiling": [43000, "ft"],
    "Fuel Consumption": [6.00, "lbs/km"],
    "Cruise Speed": [782, "kph"],
    "A-Check": [5000, "USD"],
    "Maintenance Interval": [450, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [13, "m"],
    "Length": [12, "m"]
  },
  an74vip: {
    Price: [100722, "USD"],
    Seats: [12, "passengers"],
    Range: [3300, "km"],
    "Runway Required": [4900, "ft"],
    "Service Ceiling": [30000, "ft"],
    "Fuel Consumption": [7.68, "lbs/km"],
    "Cruise Speed": [539, "kph"],
    "A-Check": [18130, "USD"],
    "Maintenance Interval": [350, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [28, "m"],
    "Length": [32, "m"]
  },
  saab340: {
    Price: [109241, "USD"],
    Seats: [37, "passengers"],
    Range: [1730, "km"],
    "Runway Required": [4600, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [13.65, "lbs/km"],
    "Cruise Speed": [425, "kph"],
    "A-Check": [19664, "USD"],
    "Maintenance Interval": [380, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.19, "kg/pax/km"],
    "Wingspan": [20, "m"],
    "Length": [21, "m"]
  },
  legacy450: {
    Price: [110501, "USD"],
    Seats: [7, "passengers"],
    Range: [4260, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [40000, "ft"],
    "Fuel Consumption": [7.60, "lbs/km"],
    "Cruise Speed": [837, "kph"],
    "A-Check": [4420, "USD"],
    "Maintenance Interval": [520, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.10, "kg/pax/km"],
    "Wingspan": [20, "m"],
    "Length": [20, "m"]
  },
  beech1900: {
    Price: [119896, "USD"],
    Seats: [19, "passengers"],
    Range: [2907, "km"],
    "Runway Required": [4500, "ft"],
    "Service Ceiling": [30000, "ft"],
    "Fuel Consumption": [9.36, "lbs/km"],
    "Cruise Speed": [500, "kph"],
    "A-Check": [21582, "USD"],
    "Maintenance Interval": [380, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    "Wingspan": [18, "m"],
    "Length": [18, "m"]
  },
  saabscan: {
    Price: [113217, "USD"],
    Seats: [32, "passengers"],
    Range: [2510, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [20000, "ft"],
    "Fuel Consumption": [9.27, "lbs/km"],
    "Cruise Speed": [477, "kph"],
    "A-Check": [42456, "USD"],
    "Maintenance Interval": [210, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [3, "people"],
    "CO2 Emission": [0.11, "kg/pax/km"],
    "Wingspan": [21, "m"],
    "Length": [28, "m"]
  },
  atr42: {
    Price: [122750, "USD"],
    Seats: [50, "passengers"],
    Range: [1611, "km"],
    "Runway Required": [6500, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [14.88, "lbs/km"],
    "Cruise Speed": [550, "kph"],
    "A-Check": [21482, "USD"],
    "Maintenance Interval": [340, "hours"],
    "Crew Total": [4, "people"],
    "Engineers": [1, "people"],
    "Tech": [1, "people"],
    "CO2 Emission": [0.20, "kg/pax/km"],
    "Wingspan": [22, "m"],
    "Length": [24, "m"]
  },
  dhc8: {
    Price: [124381, "USD"],
    Seats: [37, "passengers"],
    Range: [1713, "km"],
    "Runway Required": [2000, "ft"],
    "Service Ceiling": [25000, "ft"],
    "Fuel Consumption": [17.51, "lbs/km"],
    "Cruise Speed": [585, "kph"],
    "A-Check": [14926, "USD"],
    "Maintenance Interval": [480, "hours"],
    "Crew Total": [3, "people"],
    "Engineers": [1, "people"],
    "Tech": [2, "people"],
    "CO2 Emission": [0.21, "kg/pax/km"],
    "Wingspan": [22, "m"],
    "Length": [26, "m"]
  }
};